### ISSUE TITLE
Also requires matplotlib as dependency

### ISSUE THREAD

**Issue by Marky0** [google-research/planet#15]
python -m planet.scripts.train --params '{tasks: [cheetah_run]}'

Traceback (most recent call last):
  File "runpy.py", line 183, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "runpy.py", line 109, in _get_module_details__import__(pkg_name)
  File "planet\__init__.py", line 19, in <module>from . import control
  File "planet\control\__init__.py", line 19, in <module>from . import planning
  File "planet\planet-master\planet\control\planning.py", line 23, in <module>from planet import tools
  File "planet\tools\__init__.py", line 22, in <module>from . import summary
  File "planet\tools\summary.py", line 19, in <module>import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by danijar** [comment]
Thanks, I'll add a note with the next update.
