### ISSUE TITLE
OSError: undefined symbol: __glewBindBuffer

### ISSUE THREAD

**Issue by lls19961014** [google-research/planet#16]
Hello,when  I run PlaNet with the terminal in (ubuntu18.04,cuda10.0.130,cudnn7.3.1) :
python3 -m planet.scripts.train   --logdir ~/planet-master   --config default     --params '{tasks: [cheetah_run]}'

WARNING:tensorflow:Worker c14e0611-dcb3-43a0-86c5-a886b569ae93 run 00001: Start.
INFO:tensorflow:Collecting 5+ random episodes (test-cheetah_run).
I0403 21:33:35.180162 139990664775488 acceleratesupport.py:17] No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
I0403 21:33:35.266633 139990664775488 __init__.py:34] MuJoCo library version is: 200
INFO:tensorflow:Recorded episode 20190403T213335-5db0f651f77f497b99b330fb21a99663.
INFO:tensorflow:Recorded episode 20190403T213336-83adee5b7a1f40b1ad00c088885ae486.
INFO:tensorflow:Recorded episode 20190403T213336-458015a378c743fd8e223033725bbd2a.
INFO:tensorflow:Recorded episode 20190403T213337-cbd989f537834e3aa6c4629e18dcae4c.
INFO:tensorflow:Recorded episode 20190403T213337-7817524fc36d4f87a8d48e266941b6bd.
INFO:tensorflow:Collecting 5+ random episodes (train-cheetah_run).
INFO:tensorflow:Recorded episode 20190403T213338-6ab268afed1f486298a7c8530413f8af.
INFO:tensorflow:Recorded episode 20190403T213338-58d74c263fb145568708e5695b2e7d3a.
INFO:tensorflow:Recorded episode 20190403T213338-d77039b59d9a4773a8a2b7ef40aa6f69.
INFO:tensorflow:Recorded episode 20190403T213339-12edd59a999a4aa0ade7c61c7a9aa54c.
INFO:tensorflow:Recorded episode 20190403T213339-26402c3b172d40dba29992c0a8134687.
WARNING:tensorflow:From /home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:429: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    
WARNING:tensorflow:From /home/lls/planet-master/planet/tools/preprocess.py:24: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Start a new run and write summaries and checkpoints to /home/lls/planet-master/00001.
WARNING:tensorflow:From /home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
INFO:tensorflow:Build TensorFlow compute graph.
WARNING:tensorflow:From /home/lls/planet-master/planet/networks/conv_ha.py:30: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
WARNING:tensorflow:From /home/lls/planet-master/planet/networks/conv_ha.py:34: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/lls/planet-master/planet/tools/overshooting.py:80: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From /home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:626: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/lls/planet-master/planet/models/rssm.py:94: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
WARNING:tensorflow:Worker c14e0611-dcb3-43a0-86c5-a886b569ae93 run 00001: Exception:
Traceback (most recent call last):
  File "/home/lls/planet-master/planet/training/running.py", line 198, in __iter__
    for value in self._process_fn(self._logdir, *args):
  File "/home/lls/planet-master/planet/scripts/train.py", line 91, in process
    training.define_model, dataset, logdir, config):
  File "/home/lls/planet-master/planet/training/utility.py", line 160, in train
    score, summary = model_fn(data, trainer, config)
  File "/home/lls/planet-master/planet/training/define_model.py", line 71, in define_model
    config.overshooting + 1)
  File "/home/lls/planet-master/planet/tools/overshooting.py", line 80, in overshooting
    swap_memory=True)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 671, in dynamic_rnn
    dtype=dtype)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 879, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3525, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 845, in _time_step
    skip_conditionals=True)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 276, in _rnn_step
    new_output, new_state = call_cell()
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 833, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 234, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 534, in __call__
    _add_elements_to_collection(self.updates, ops.GraphKeys.UPDATE_OPS)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 653, in updates
    return self._updates + self._gather_children_attribute('updates')
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1646, in _gather_children_attribute
    getattr(layer, attribute) for layer in self._layers))
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1646, in <genexpr>
    getattr(layer, attribute) for layer in self._layers))
AttributeError: 'Template' object has no attribute 'updates'

How to deal with this error?Thank you  ^_^

**Comment by danijar** [comment]
What's your TensorFlow version? Does it match the one mentioned in the readme?

**Comment by lls19961014** [comment]
yes,  tensorflow-gpu==1.13.1 and tensorflow-probability==0.6.0
But the code was downloaded two weeks ago. When I run the lastest code version ,this error is gone.
When I click the PyCharm's RUN button ,it runs successfully.But when I use the  terminal with the same interpreter ,another error raised: 
 WARNING:tensorflow:Worker 7c829fd1-681c-463d-a6ed-e2cd118d29a1 run 00001: Create directory '/home/lls/download/planet-master/00001'.
WARNING:tensorflow:Worker 7c829fd1-681c-463d-a6ed-e2cd118d29a1 run 00001: Start.
INFO:tensorflow:Collecting 5 initial episodes (test-cheetah_run).
W0404 09:47:12.196148 140591745066816 __init__.py:36] mjbindings failed to import mjlib and other functions. libmujoco.so may not be accessible.
WARNING:tensorflow:Worker 7c829fd1-681c-463d-a6ed-e2cd118d29a1 run 00001: Exception:
Traceback (most recent call last):
  File "/home/lls/download/planet-master/planet/training/running.py", line 199, in __iter__
    for value in self._process_fn(self._logdir, *args):
  File "/home/lls/download/planet-master/planet/scripts/train.py", line 64, in process
    training.utility.collect_initial_episodes(config)
  File "/home/lls/download/planet-master/planet/training/utility.py", line 286, in collect_initial_episodes
    control.random_episodes(params.task.env_ctor, remaining, outdir)
  File "/home/lls/download/planet-master/planet/control/random_episodes.py", line 23, in random_episodes
    env = env_ctor()
  File "/home/lls/download/planet-master/planet/scripts/tasks.py", line 120, in _dm_control_env
    from dm_control import suite
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/suite/__init__.py", line 28, in <module>
    from dm_control.suite import acrobot
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/suite/acrobot.py", line 24, in <module>
    from dm_control import mujoco
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
    from dm_control.mujoco.engine import action_spec
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/engine.py", line 44, in <module>
    from dm_control.mujoco import index
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/index.py", line 92, in <module>
    from dm_control.mujoco.wrapper import util
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/__init__.py", line 25, in <module>
    from dm_control.mujoco.wrapper.core import callback_context
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 32, in <module>
    from dm_control.mujoco.wrapper.mjbindings import functions
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/mjbindings/functions.py", line 21, in <module>
    mjlib = util.get_mjlib()
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/util.py", line 127, in get_mjlib
    return ctypes.cdll.LoadLibrary(library_path)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/lls/.mujoco/mujoco200_linux/bin/libmujoco200.so: undefined symbol: __glewBindBuffer

**Comment by danijar** [comment]
Yes, I added support for TensorFlow 1.13.1 in a recent update. Your new issue is related to rendering in dm_control. Did you follow the instructions in the dm_control readme? If this doesn't work for you please try all three rendering options ('glfw`, `egl`, `osmesa`).

**Comment by lls19961014** [comment]
Yes,the mujuco 200 was installed successfully,and then I use the "pip install git+git://github.com/deepmind/dm_control.git".I can see the dm_control 0.0.0 pkgs in interpreter package lists

**Comment by danijar** [comment]
Did you try the different rendering options? If that doesn't work, please try to create a dm_control environment (`suite.load('cheetah', 'run')`) and render it (`env.physics.render()`) in a self-contined script outside of the PlaNet code.

**Comment by lls19961014** [comment]
Thank you.I will have a try.

**Comment by danijar** [comment]
Closing this for now. If you still run into problems please comment here so we can reopen it.

**Comment by tinyzqh** [comment]
> yes, tensorflow-gpu==1.13.1 and tensorflow-probability==0.6.0
> But the code was downloaded two weeks ago. When I run the lastest code version ,this error is gone.
> When I click the PyCharm's RUN button ,it runs successfully.But when I use the terminal with the same interpreter ,another error raised:
> WARNING:tensorflow:Worker 7c829fd1-681c-463d-a6ed-e2cd118d29a1 run 00001: Create directory '/home/lls/download/planet-master/00001'.
> WARNING:tensorflow:Worker 7c829fd1-681c-463d-a6ed-e2cd118d29a1 run 00001: Start.
> INFO:tensorflow:Collecting 5 initial episodes (test-cheetah_run).
> W0404 09:47:12.196148 140591745066816 **init**.py:36] mjbindings failed to import mjlib and other functions. libmujoco.so may not be accessible.
> WARNING:tensorflow:Worker 7c829fd1-681c-463d-a6ed-e2cd118d29a1 run 00001: Exception:
> Traceback (most recent call last):
> File "/home/lls/download/planet-master/planet/training/running.py", line 199, in **iter**
> for value in self._process_fn(self._logdir, *args):
> File "/home/lls/download/planet-master/planet/scripts/train.py", line 64, in process
> training.utility.collect_initial_episodes(config)
> File "/home/lls/download/planet-master/planet/training/utility.py", line 286, in collect_initial_episodes
> control.random_episodes(params.task.env_ctor, remaining, outdir)
> File "/home/lls/download/planet-master/planet/control/random_episodes.py", line 23, in random_episodes
> env = env_ctor()
> File "/home/lls/download/planet-master/planet/scripts/tasks.py", line 120, in _dm_control_env
> from dm_control import suite
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/suite/**init**.py", line 28, in
> from dm_control.suite import acrobot
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/suite/acrobot.py", line 24, in
> from dm_control import mujoco
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/**init**.py", line 18, in
> from dm_control.mujoco.engine import action_spec
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/engine.py", line 44, in
> from dm_control.mujoco import index
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/index.py", line 92, in
> from dm_control.mujoco.wrapper import util
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/**init**.py", line 25, in
> from dm_control.mujoco.wrapper.core import callback_context
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 32, in
> from dm_control.mujoco.wrapper.mjbindings import functions
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/mjbindings/functions.py", line 21, in
> mjlib = util.get_mjlib()
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/site-packages/dm_control/mujoco/wrapper/util.py", line 127, in get_mjlib
> return ctypes.cdll.LoadLibrary(library_path)
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/ctypes/**init**.py", line 426, in LoadLibrary
> return self._dlltype(name)
> File "/home/lls/anaconda3/envs/planet-master/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> self._handle = _dlopen(self._name, mode)
> OSError: /home/lls/.mujoco/mujoco200_linux/bin/libmujoco200.so: undefined symbol: __glewBindBuffer

I see the same problem, because the pycharm can't load the LD_LIBRARY_PATH of .bashrc. 
I resolved this problem after starting PyCharm from the terminal.
