### ISSUE TITLE
InvalidArgumentError: Found Inf or NaN global norm. : Tensor had Inf values

### ISSUE THREAD

**Issue by doralune** [google-research/planet#18]
The error below occurred at epoch 120 when I run the training of the gym_racecar task.
Does anyone know how to avoid this ? I will try again and look into the code. 

<details>
<summary>
Training script
</summary>

```
CUDA_VISIBLE_DEVICES="1" \
xvfb-run -s "-screen 0 1024x768x24" \
python -m planet.scripts.train  \
    --logdir "../out/train/e_6" \
    --num_runs "1" \
    --config "default" \
    --params "{tasks: [gym_racecar]}" \
    --ping_every 0 \
    --resume_runs "False"
```

</details>

<details>
<summary>
Error message
</summary>

```
WARNING:tensorflow:Worker fc7e16f7-62a8-4cc9-bdc2-e41718f6ee3d run 00001: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had Inf values
     [[{{node graph/optimizer_main/VerifyFinite/CheckNumerics}}]]
     [[{{node GroupCrossDeviceControlEdges_0/graph/phase_train/cond_2/trainer/train/score/tags}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/share/planet/planet/training/running.py", line 199, in __iter__
    for value in self._process_fn(self._logdir, *args):
  File "/root/share/planet/planet/scripts/train.py", line 78, in process
    training.define_model, dataset, logdir, config):
  File "/root/share/planet/planet/training/utility.py", line 179, in train
    for score in trainer.iterate(config.max_steps):
  File "/root/share/planet/planet/training/trainer.py", line 201, in iterate
    summary, mean_score, global_step = sess.run(phase.op, phase.feed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had Inf values
     [[node graph/optimizer_main/VerifyFinite/CheckNumerics (defined at /root/share/planet/planet/tools/custom_optimizer.py:46) ]]
     [[{{node GroupCrossDeviceControlEdges_0/graph/phase_train/cond_2/trainer/train/score/tags}}]]

Caused by op 'graph/optimizer_main/VerifyFinite/CheckNumerics', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/share/planet/planet/scripts/train.py", line 118, in <module>
    tf.app.run(lambda _: main(args_), remaining)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/share/planet/planet/scripts/train.py", line 118, in <lambda>
    tf.app.run(lambda _: main(args_), remaining)
  File "/root/share/planet/planet/scripts/train.py", line 91, in main
    for unused_score in run:
  File "/root/share/planet/planet/training/running.py", line 199, in __iter__
    for value in self._process_fn(self._logdir, *args):
  File "/root/share/planet/planet/scripts/train.py", line 78, in process
    training.define_model, dataset, logdir, config):
  File "/root/share/planet/planet/training/utility.py", line 160, in train
    score, summary = model_fn(data, trainer, config)
  File "/root/share/planet/planet/training/define_model.py", line 111, in define_model
    train_loss, step, should_summarize, config.optimizers)
  File "/root/share/planet/planet/training/utility.py", line 221, in apply_optimizers
    optimize, opt_summary = optimizer.minimize(loss)
  File "/root/share/planet/planet/tools/custom_optimizer.py", line 46, in minimize
    gradients, self._clipping, gradient_norm)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/clip_ops.py", line 271, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/numerics.py", line 44, in verify_tensor_all_finite
    return verify_tensor_all_finite_v2(t, msg, name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/numerics.py", line 62, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 919, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had Inf values
     [[node graph/optimizer_main/VerifyFinite/CheckNumerics (defined at /root/share/planet/planet/tools/custom_optimizer.py:46) ]]
     [[{{node GroupCrossDeviceControlEdges_0/graph/phase_train/cond_2/trainer/train/score/tags}}]]


WARNING:tensorflow:Worker fc7e16f7-62a8-4cc9-bdc2-e41718f6ee3d run 00001: Failed.
```

</details>

**Comment by danijar** [comment]
Hey, the Gym tasks don't work yet, I just started to integrate them into the code base. We only support the dm_control tasks at this point.

If you're interested, I'd be delighted if you'd look into getting them to run. The main problem I'm facing with racecar is rendering: most of the frames that end up in the dataset are completely black.
