### ISSUE TITLE
'GFile' object has no attribute 'seekable'

### ISSUE THREAD

**Issue by JuliusKunze** [google-research/planet#46]
Training with the default config on macOS with `tensorflow==1.13.1` in python 3.7.0 (same in 3.6.8) records some episodes before failing with:

```python
Traceback (most recent call last):
  File "/Users/juliuskunze/prj/planet/planet/training/running.py", line 201, in __iter__
    for value in self._process_fn(self._logdir, *args):
  File "/Users/juliuskunze/prj/planet/planet/scripts/train.py", line 71, in process
    preprocess_fn=config.preprocess_fn)
  File "/Users/juliuskunze/prj/planet/planet/tools/numpy_episodes.py", line 51, in numpy_episodes
    dtypes, shapes = _read_spec(reader, train_dir)
  File "/Users/juliuskunze/prj/planet/planet/tools/numpy_episodes.py", line 149, in _read_spec
    episode = next(episodes)
  File "/Users/juliuskunze/prj/planet/planet/tools/numpy_episodes.py", line 110, in reload_loader
    yield reader(filename)
  File "/Users/juliuskunze/prj/planet/planet/tools/numpy_episodes.py", line 132, in episode_reader
    episode = {key: _convert_type(episode[key]) for key in episode.keys()}
  File "/Users/juliuskunze/prj/planet/planet/tools/numpy_episodes.py", line 132, in <dictcomp>
    episode = {key: _convert_type(episode[key]) for key in episode.keys()}
  File "/Users/juliuskunze/.pyenv/versions/3.7.0/envs/tf-planet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 255, in __getitem__
    bytes = self.zip.open(key)
  File "/Users/juliuskunze/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 1458, in open
    self._fpclose, self._lock, lambda: self._writing)
  File "/Users/juliuskunze/.pyenv/versions/3.7.0/lib/python3.7/zipfile.py", line 699, in __init__
    self.seekable = file.seekable
AttributeError: 'GFile' object has no attribute 'seekable'
```

**Comment by danijar** [comment]
Did the workaround in the `CollectGymDataset` wrapper help? Replacing

```python
with io.BytesIO() as file_:
  np.savez_compressed(file_, **episode)
  file_.seek(0)
  with tf.gfile.Open(filename, 'w') as ff:
    ff.write(file_.read())
```

with

```python
np.savez_compressed(filename, **episode)
```

**Comment by JuliusKunze** [comment]
Unfortunately not, symptoms are unchanged!

**Comment by danijar** [comment]
Oh, I see this is when reading episodes, not when storing them. It's probably line 130 in `tools/numpy_episodes.py`. You can change it from

```python
with tf.gfile.Open(filename, 'rb') as file_:
    episode = np.load(file_)
```

to

```python
episode = np.load(filename)
```

**Comment by JuliusKunze** [comment]
Thanks, fixes the issue
