### ISSUE TITLE
error when run running sample command

### ISSUE THREAD

**Issue by sharr6** [google-research/planet#48]
Hi,
Impressing work!
When I run the sample command     python3 -m planet.scripts.train --logdir /path/to/logdir --config default --params '{tasks: [cheetah_run]}'
I get an error:

Traceback (most recent call last):
  File "/media/shar/Runtime/LinRuntime/planet-master/planet/scripts/train.py", line 110, in <module>
    args_.params = tools.AttrDict(yaml.safe_load(args_.params.replace('#', ',')))
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/main.py", line 980, in safe_load
    return load(stream, SafeLoader, version)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 73, in get_single_node
    self.parser.get_event()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/parser.py", line 163, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/parser.py", line 177, in parse_stream_start
    token.move_comment(self.scanner.peek_token())
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/scanner.py", line 182, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/scanner.py", line 306, in fetch_more_tokens
    return self.fetch_single()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/scanner.py", line 724, in fetch_single
    self.fetch_flow_scalar(style="'")
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/scanner.py", line 737, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/scanner.py", line 1380, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/scanner.py", line 1479, in scan_flow_scalar_spaces
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: while scanning a quoted scalar
  in "<unicode string>", line 1, column 1:
    '{tasks:
    ^ (line: 1)
found unexpected end of stream
  in "<unicode string>", line 1, column 9:
    '{tasks:
            ^ (line: 1)

Process finished with exit code 1

any advice how can i run it right?

**Comment by danijar** [comment]
Have you tried double quotes around the parameters instead of single quotes? It seems like your shell sends the params as two separate flags because of the space.
