### ISSUE TITLE
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shinian123** [google-research/planet#7]
When I run PlaNet, 
python planet/scripts/train.py  --logdir ./data --config default --params '{tasks: [cheetah_run]}'
then shows:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/anaconda3/envs/py3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/anaconda3/envs/py3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "planet/scripts/train.py", line 51, in <module>
    import tensorflow as tf
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/anaconda3/envs/py3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/anaconda3/envs/py3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

I install tensorflow for 1.13.1 and cuda100 from anaconda cloud, but it still does not work.

**Comment by doralune** [comment]
@shinian123
Setting the LD_LIBRARY_PATH that includes the libcublas.so.10.0 when running as below might solve your problem.
```
# Try to see if tensorflow could be imported
$ LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64 python -c "import tensorflow" 
```
The libcublas.so.10.0 is supposed to be in /usr/local/cuda-10.0/lib64 as default of the cuda10.0 installation.

**Comment by danijar** [comment]
@shinian123 As @doralune pointed out, please make sure that TensorFlow with GPU support works for you before running the PlaNet code.
